
metrics: 
  - metric_name: cka
    target_checkpoint: 100
    components: 
      - name: ov_circuit
        layer_suffixes: 
          output_layer: "attention.o_proj"
          value_layer: "attention.v_proj"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
      - name: mlp
        layer_suffixes:
          mlp: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]

steps: 
  start: 0
  end: 100
  step: 50
