analysis_name: "pico-decoder-demo-2-analysis"

metrics: 
  - metric_name: cka
    target_checkpoint: 100
    data_split: "val"
    components: 
      - component_name: ov_circuit
        data_type: "activations"
        layer_suffixes: 
          output_layer: "attention.o_proj"
          value_layer: "attention.v_proj"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
      - component_name: simple
        data_type: "activations"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  - metric_name: per
    data_split: "train"
    components: 
      - component_name: simple
        data_type: "weights"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  - metric_name: condition_number
    data_split: "train"
    components: 
      - component_name: simple
        data_type: "weights"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  - metric_name: gini
    data_split: "val"
    components: 
      - component_name: simple
        data_type: "weights"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  - metric_name: hoyer
    data_split: "val"
    components: 
      - component_name: simple
        data_type: "weights"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  - metric_name: pwcca
    target_checkpoint: 50
    data_split: "train"
    components: 
      - component_name: ov_circuit
        data_type: "activations"
        layer_suffixes: 
          output_layer: "attention.o_proj"
          value_layer: "attention.v_proj"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  - metric_name: norm
    data_split: "val"
    norm_type: "nuclear"
    components: 
      - component_name: ov_circuit
        data_type: "weights"
        layer_suffixes: 
          output_layer: "attention.o_proj"
          value_layer: "attention.v_proj"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
        

steps: 
  start: 0
  end: 100
  step: 50

monitoring: 
  output_dir: "analysis_results"

  save_to_wandb: false
  wandb:
    entity: "pico-lm"
    project: "pico-demo"
